
import type { Influencer, Campaign } from './types';

export const influencers: Influencer[] = [
  {
    id: 'inf-1',
    name: 'Alexina Jordan',
    platform: 'YouTube',
    channelName: 'Alexina\'s Tech',
    category: 'Tech',
    language: 'English',
    region: 'USA',
    channelLink: 'https://youtube.com/alexina',
    handle: 'alexinatech',
    email: 'alexina@example.com',
    mobile: '+1-202-555-0176',
    pan: 'ABCDE1234F',
    agency: {
      name: 'TechStars Agency',
      contact: 'contact@techstars.com',
    },
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-05-20',
    lastPricePaid: 5000,
    averageViews: 150000,
    avatar: 'https://picsum.photos/seed/1/100/100',
  },
  {
    id: 'inf-2',
    name: 'Ben Carter',
    platform: 'Instagram',
    channelName: 'Ben Carter Style',
    category: 'Fashion',
    language: 'English',
    region: 'UK',
    channelLink: 'https://instagram.com/bencarterstyle',
    handle: 'bencarterstyle',
    email: 'ben.carter@example.com',
    mobile: '+44-20-7946-0958',
    pan: 'FGHIJ5678K',
    lastPromotionBy: 'Sales',
    lastPromotionDate: '2024-06-15',
    lastPricePaid: 3500,
    averageViews: 80000,
    avatar: 'https://picsum.photos/seed/2/100/100',
  },
  {
    id: 'inf-5',
    name: 'Elena Garcia',
    platform: 'YouTube',
    channelName: 'Vida de Elena',
    category: 'Lifestyle',
    language: 'Spanish',
    region: 'Spain',
    channelLink: 'https://youtube.com/elenagarcia',
    handle: 'elenagarciavida',
    email: 'elena.garcia@example.com',
    mobile: '+34-91-123-45-67',
    pan: 'VWXYZ7890N',
    agency: {
      name: 'Vida Social',
      contact: 'hola@vidasocial.es',
    },
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-04-22',
    lastPricePaid: 6000,
    averageViews: 250000,
    avatar: 'https://picsum.photos/seed/5/100/100',
  },
  {
    id: 'inf-6',
    name: 'Fumiko Tanaka',
    platform: 'Instagram',
    channelName: 'Fumiko Eats',
    category: 'Food',
    language: 'Japanese',
    region: 'Japan',
    channelLink: 'https://instagram.com/fumikoeats',
    handle: 'fumikoeats',
    email: 'fumiko.tanaka@example.com',
    mobile: '+81-3-1234-5678',
    pan: 'BCDA1234E',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-02-18',
    lastPricePaid: 2800,
    averageViews: 120000,
    avatar: 'https://picsum.photos/seed/6/100/100',
  },
  {
    id: 'inf-8',
    name: 'Hannah Schmidt',
    platform: 'YouTube',
    channelName: 'Hannah Lernt',
    category: 'Education',
    language: 'German',
    region: 'Germany',
    channelLink: 'https://youtube.com/hannahschmidt',
    handle: 'hannahlernt',
    email: 'hannah.schmidt@example.com',
    mobile: '+49-30-1234567',
    pan: 'MNOPQ3456G',
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-05-30',
    lastPricePaid: 4800,
    averageViews: 180000,
    avatar: 'https://picsum.photos/seed/8/100/100',
  },
  {
    id: 'inf-10',
    name: 'Jasmine Chen',
    platform: 'Instagram',
    channelName: 'Jasmine Travels',
    category: 'Travel',
    language: 'Mandarin',
    region: 'China',
    channelLink: 'https://instagram.com/jasminetravels',
    handle: 'jasminetravels',
    email: 'jasmine.chen@example.com',
    mobile: '+86-10-1234-5678',
    pan: 'WXYZA5678I',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-01-12',
    lastPricePaid: 7000,
    averageViews: 200000,
    avatar: 'https://picsum.photos/seed/10/100/100',
  },
  {
    id: 'inf-11',
    name: 'Liam Murphy',
    platform: 'YouTube',
    channelName: 'Liam\'s Garage',
    category: 'Automotive',
    language: 'English',
    region: 'Canada',
    channelLink: 'https://youtube.com/liamsgarage',
    handle: 'liamsgarage',
    email: 'liam.murphy@example.com',
    mobile: '+1-416-555-0192',
    pan: 'PQRS6789J',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-07-10',
    lastPricePaid: 5500,
    averageViews: 175000,
    avatar: 'https://picsum.photos/seed/11/100/100',
  },
  {
    id: 'inf-12',
    name: 'Sofia Rossi',
    platform: 'Instagram',
    channelName: 'Art by Sofia',
    category: 'Art',
    language: 'Italian',
    region: 'Italy',
    channelLink: 'https://instagram.com/artbysofia',
    handle: 'artbysofia',
    email: 'sofia.rossi@example.com',
    mobile: '+39-06-12345678',
    pan: 'KLMN0123K',
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-03-25',
    lastPricePaid: 4000,
    averageViews: 95000,
    avatar: 'https://picsum.photos/seed/12/100/100',
  },
  {
    id: 'inf-13',
    name: 'Lucas Silva',
    platform: 'YouTube',
    channelName: 'Brasil Fitness',
    category: 'Fitness',
    language: 'Portuguese',
    region: 'Brazil',
    channelLink: 'https://youtube.com/brasilfitness',
    handle: 'brasilfitness',
    email: 'lucas.silva@example.com',
    mobile: '+55-11-91234-5678',
    pan: 'UVWX4567L',
    lastPromotionBy: 'Sales',
    lastPromotionDate: '2024-06-05',
    lastPricePaid: 3800,
    averageViews: 130000,
    avatar: 'https://picsum.photos/seed/13/100/100',
  },
  {
    id: 'inf-14',
    name: 'Aisha Khan',
    platform: 'Instagram',
    channelName: 'Aisha\'s Beauty Book',
    category: 'Beauty',
    language: 'Hindi',
    region: 'India',
    channelLink: 'https://instagram.com/aishasbeautybook',
    handle: 'aishasbeautybook',
    email: 'aisha.khan@example.com',
    mobile: '+91-9876543210',
    pan: 'YZAB8901M',
    agency: {
      name: 'Glam India',
      contact: 'contact@glamindia.com',
    },
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-05-18',
    lastPricePaid: 3000,
    averageViews: 110000,
    avatar: 'https://picsum.photos/seed/14/100/100',
  },
];

export const campaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Summer Fashion Launch',
    department: 'Sales',
    deliverables: '2 Instagram Posts, 3 Stories',
    date: '2024-06-15',
    pricePaid: 3500,
    averageViews: 80000,
    influencerId: 'inf-2',
    approvalStatus: 'Approved',
  },
  {
    id: 'camp-2',
    name: 'New Gadget Unboxing',
    department: 'Marketing',
    deliverables: '1 YouTube Video',
    date: '2024-05-20',
    pricePaid: 5000,
    averageViews: 150000,
    influencerId: 'inf-1',
    approvalStatus: 'Pending',
  },
  {
    id: 'camp-3',
    name: 'Comedy Skit Collab',
    department: 'Product',
    deliverables: '3 TikTok Videos',
    date: '2023-11-10',
    pricePaid: 2000,
    averageViews: 500000,
    influencerId: 'inf-3',
    approvalStatus: 'Approved',
  },
  {
    id: 'camp-4',
    name: 'Gaming Tournament Stream',
    department: 'Marketing',
    deliverables: '4 hour stream on Twitter',
    date: '2024-07-01',
    pricePaid: 4200,
    averageViews: 45000,
    influencerId: 'inf-4',
    approvalStatus: 'Approved',
  },
  {
    id: 'camp-5',
    name: 'Lifestyle Vlog Series',
    department: 'Brand',
    deliverables: '3 YouTube Videos',
    date: '2024-04-22',
    pricePaid: 6000,
    averageViews: 250000,
    influencerId: 'inf-5',
    approvalStatus: 'Rejected',
  },
  {
    id: 'camp-6',
    name: 'Japanese Food Tour',
    department: 'Marketing',
    deliverables: '5 Instagram Posts',
    date: '2024-02-18',
    pricePaid: 2800,
    averageViews: 120000,
    influencerId: 'inf-6',
    approvalStatus: 'Approved',
  },
];
