
import type { Influencer, Campaign } from './types';

export const influencers: Influencer[] = [
  {
    id: 'inf-1',
    name: 'Alexina Jordan',
    platform: 'YouTube',
    category: 'Tech',
    language: 'English',
    region: 'USA',
    channelLink: 'https://youtube.com/alexina',
    handle: 'alexinatech',
    email: 'alexina@example.com',
    mobile: '+1-202-555-0176',
    pan: 'ABCDE1234F',
    agency: {
      name: 'TechStars Agency',
      contact: 'contact@techstars.com',
    },
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-05-20',
    lastPricePaid: 5000,
    averageViews: 150000,
    avatar: 'https://picsum.photos/seed/1/100/100',
  },
  {
    id: 'inf-2',
    name: 'Ben Carter',
    platform: 'Instagram',
    category: 'Fashion',
    language: 'English',
    region: 'UK',
    channelLink: 'https://instagram.com/bencarterstyle',
    handle: 'bencarterstyle',
    email: 'ben.carter@example.com',
    mobile: '+44-20-7946-0958',
    pan: 'FGHIJ5678K',
    lastPromotionBy: 'Sales',
    lastPromotionDate: '2024-06-15',
    lastPricePaid: 3500,
    averageViews: 80000,
    avatar: 'https://picsum.photos/seed/2/100/100',
  },
  {
    id: 'inf-3',
    name: 'Chloé Dubois',
    platform: 'TikTok',
    category: 'Comedy',
    language: 'French',
    region: 'France',
    channelLink: 'https://tiktok.com/@chloedrole',
    handle: 'chloedrole',
    email: 'chloe.dubois@example.com',
    mobile: '+33-1-23-45-67-89',
    pan: 'LMNOP9012L',
    lastPromotionBy: 'Product',
    lastPromotionDate: '2023-11-10',
    lastPricePaid: 2000,
    averageViews: 500000,
    avatar: 'https://picsum.photos/seed/3/100/100',
  },
  {
    id: 'inf-4',
    name: 'David Kim',
    platform: 'Twitter',
    category: 'Gaming',
    language: 'Korean',
    region: 'South Korea',
    channelLink: 'https://twitter.com/davidkimplays',
    handle: 'davidkimplays',
    email: 'david.kim@example.com',
    mobile: '+82-2-1234-5678',
    pan: 'QRSTU3456M',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-07-01',
    lastPricePaid: 4200,
    averageViews: 45000,
    avatar: 'https://picsum.photos/seed/4/100/100',
  },
  {
    id: 'inf-5',
    name: 'Elena Garcia',
    platform: 'YouTube',
    category: 'Lifestyle',
    language: 'Spanish',
    region: 'Spain',
    channelLink: 'https://youtube.com/elenagarcia',
    handle: 'elenagarciavida',
    email: 'elena.garcia@example.com',
    mobile: '+34-91-123-45-67',
    pan: 'VWXYZ7890N',
    agency: {
      name: 'Vida Social',
      contact: 'hola@vidasocial.es',
    },
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-04-22',
    lastPricePaid: 6000,
    averageViews: 250000,
    avatar: 'https://picsum.photos/seed/5/100/100',
  },
  {
    id: 'inf-6',
    name: 'Fumiko Tanaka',
    platform: 'Instagram',
    category: 'Food',
    language: 'Japanese',
    region: 'Japan',
    channelLink: 'https://instagram.com/fumikoeats',
    handle: 'fumikoeats',
    email: 'fumiko.tanaka@example.com',
    mobile: '+81-3-1234-5678',
    pan: 'BCDA1234E',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-02-18',
    lastPricePaid: 2800,
    averageViews: 120000,
    avatar: 'https://picsum.photos/seed/6/100/100',
  },
  {
    id: 'inf-7',
    name: 'George Williams',
    platform: 'TikTok',
    category: 'DIY',
    language: 'English',
    region: 'Australia',
    channelLink: 'https://tiktok.com/@georgedoesdiy',
    handle: 'georgedoesdiy',
    email: 'george.w@example.com',
    mobile: '+61-2-1234-5678',
    pan: 'HIJKL2345F',
    lastPromotionBy: 'Product',
    lastPromotionDate: '2023-09-05',
    lastPricePaid: 1500,
    averageViews: 300000,
    avatar: 'https://picsum.photos/seed/7/100/100',
  },
  {
    id: 'inf-8',
    name: 'Hannah Schmidt',
    platform: 'YouTube',
    category: 'Education',
    language: 'German',
    region: 'Germany',
    channelLink: 'https://youtube.com/hannahschmidt',
    handle: 'hannahlernt',
    email: 'hannah.schmidt@example.com',
    mobile: '+49-30-1234567',
    pan: 'MNOPQ3456G',
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-05-30',
    lastPricePaid: 4800,
    averageViews: 180000,
    avatar: 'https://picsum.photos/seed/8/100/100',
  },
  {
    id: 'inf-9',
    name: 'Ivan Petrov',
    platform: 'Twitter',
    category: 'Finance',
    language: 'Russian',
    region: 'Russia',
    channelLink: 'https://twitter.com/ivanpetrovfins',
    handle: 'ivanpetrovfins',
    email: 'ivan.petrov@example.com',
    mobile: '+7-495-123-45-67',
    pan: 'RSTUV4567H',
    agency: {
      name: 'FinConnect',
      contact: 'info@finconnect.ru',
    },
    lastPromotionBy: 'Sales',
    lastPromotionDate: '2024-06-25',
    lastPricePaid: 3200,
    averageViews: 25000,
    avatar: 'https://picsum.photos/seed/9/100/100',
  },
  {
    id: 'inf-10',
    name: 'Jasmine Chen',
    platform: 'Instagram',
    category: 'Travel',
    language: 'Mandarin',
    region: 'China',
    channelLink: 'https://instagram.com/jasminetravels',
    handle: 'jasminetravels',
    email: 'jasmine.chen@example.com',
    mobile: '+86-10-1234-5678',
    pan: 'WXYZA5678I',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-01-12',
    lastPricePaid: 7000,
    averageViews: 200000,
    avatar: 'https://picsum.photos/seed/10/100/100',
  },
];

export const campaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Summer Fashion Launch',
    department: 'Sales',
    deliverables: '2 Instagram Posts, 3 Stories',
    date: '2024-06-15',
    pricePaid: 3500,
    averageViews: 80000,
    influencerId: 'inf-2',
  },
  {
    id: 'camp-2',
    name: 'New Gadget Unboxing',
    department: 'Marketing',
    deliverables: '1 YouTube Video',
    date: '2024-05-20',
    pricePaid: 5000,
    averageViews: 150000,
    influencerId: 'inf-1',
  },
];
