
import type { Influencer, Campaign } from './types';

export const influencers: Influencer[] = [
  {
    id: 'inf-1',
    name: 'Alexina Jordan',
    platforms: [
      {
        platform: 'YouTube',
        channelName: "Alexina's Tech",
        channelLink: 'https://youtube.com/alexina',
        handle: 'alexinatech',
        averageViews: 150000,
      },
      {
        platform: 'Instagram',
        channelName: 'Alexina.Tech',
        channelLink: 'https://instagram.com/alexina.tech',
        handle: 'alexina.tech',
        averageViews: 45000,
      }
    ],
    category: 'Tech',
    language: 'English',
    email: 'alexina@example.com',
    mobile: '+1-202-555-0176',
    pan: 'ABCDE1234F',
    agency: {
      name: 'TechStars Agency',
      contact: 'contact@techstars.com',
    },
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-05-20',
    lastPricePaid: 5000,
    avatar: 'https://picsum.photos/seed/1/100/100',
  },
  {
    id: 'inf-2',
    name: 'Ben Carter',
    platforms: [{
        platform: 'Instagram',
        channelName: 'Ben Carter Style',
        channelLink: 'https://instagram.com/bencarterstyle',
        handle: 'bencarterstyle',
        averageViews: 80000,
    }],
    category: 'Fashion',
    language: 'English',
    email: 'ben.carter@example.com',
    mobile: '+44-20-7946-0958',
    pan: 'FGHIJ5678K',
    lastPromotionBy: 'Sales',
    lastPromotionDate: '2024-06-15',
    lastPricePaid: 3500,
    avatar: 'https://picsum.photos/seed/2/100/100',
  },
  {
    id: 'inf-5',
    name: 'Elena Garcia',
    platforms: [{
        platform: 'YouTube',
        channelName: 'Vida de Elena',
        channelLink: 'https://youtube.com/elenagarcia',
        handle: 'elenagarciavida',
        averageViews: 250000,
    }],
    category: 'Lifestyle',
    language: 'English',
    email: 'elena.garcia@example.com',
    mobile: '+34-91-123-45-67',
    pan: 'VWXYZ7890N',
    agency: {
      name: 'Vida Social',
      contact: 'hola@vidasocial.es',
    },
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-04-22',
    lastPricePaid: 6000,
    avatar: 'https://picsum.photos/seed/5/100/100',
  },
  {
    id: 'inf-6',
    name: 'Fumiko Tanaka',
    platforms: [{
        platform: 'Instagram',
        channelName: 'Fumiko Eats',
        channelLink: 'https://instagram.com/fumikoeats',
        handle: 'fumikoeats',
        averageViews: 120000,
    }],
    category: 'Food',
    language: 'English',
    email: 'fumiko.tanaka@example.com',
    mobile: '+81-3-1234-5678',
    pan: 'BCDA1234E',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-02-18',
    lastPricePaid: 2800,
    avatar: 'https://picsum.photos/seed/6/100/100',
  },
  {
    id: 'inf-8',
    name: 'Hannah Schmidt',
    platforms: [{
        platform: 'YouTube',
        channelName: 'Hannah Lernt',
        channelLink: 'https://youtube.com/hannahschmidt',
        handle: 'hannahlernt',
        averageViews: 180000,
    }],
    category: 'Education',
    language: 'English',
    email: 'hannah.schmidt@example.com',
    mobile: '+49-30-1234567',
    pan: 'MNOPQ3456G',
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-05-30',
    lastPricePaid: 4800,
    avatar: 'https://picsum.photos/seed/8/100/100',
  },
  {
    id: 'inf-10',
    name: 'Jasmine Chen',
    platforms: [{
        platform: 'Instagram',
        channelName: 'Jasmine Travels',
        channelLink: 'https://instagram.com/jasminetravels',
        handle: 'jasminetravels',
        averageViews: 200000,
    }],
    category: 'Travel',
    language: 'English',
    email: 'jasmine.chen@example.com',
    mobile: '+86-10-1234-5678',
    pan: 'WXYZA5678I',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-01-12',
    lastPricePaid: 7000,
    avatar: 'https://picsum.photos/seed/10/100/100',
  },
  {
    id: 'inf-11',
    name: 'Liam Murphy',
    platforms: [
        {
            platform: 'YouTube',
            channelName: "Liam's Garage",
            channelLink: 'https://youtube.com/liamsgarage',
            handle: 'liamsgarage',
            averageViews: 175000,
        },
        {
            platform: 'Instagram',
            channelName: 'Liam Drives',
            channelLink: 'https://instagram.com/liamdrives',
            handle: 'liamdrives',
            averageViews: 60000,
        }
    ],
    category: 'Automotive',
    language: 'English',
    email: 'liam.murphy@example.com',
    mobile: '+1-416-555-0192',
    pan: 'PQRS6789J',
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-07-10',
    lastPricePaid: 5500,
    avatar: 'https://picsum.photos/seed/11/100/100',
  },
  {
    id: 'inf-12',
    name: 'Sofia Rossi',
    platforms: [{
        platform: 'Instagram',
        channelName: 'Art by Sofia',
        channelLink: 'https://instagram.com/artbysofia',
        handle: 'artbysofia',
        averageViews: 95000,
    }],
    category: 'Art',
    language: 'English',
    email: 'sofia.rossi@example.com',
    mobile: '+39-06-12345678',
    pan: 'KLMN0123K',
    lastPromotionBy: 'Brand',
    lastPromotionDate: '2024-03-25',
    lastPricePaid: 4000,
    avatar: 'https://picsum.photos/seed/12/100/100',
  },
  {
    id: 'inf-13',
    name: 'Priya Sharma',
    platforms: [{
        platform: 'YouTube',
        channelName: 'Bolly Fitness',
        channelLink: 'https://youtube.com/bollyfitness',
        handle: 'bollyfitness',
        averageViews: 130000,
    }],
    category: 'Fitness',
    language: 'Hindi',
    email: 'priya.sharma@example.com',
    mobile: '+91-11-91234-5678',
    pan: 'UVWX4567L',
    lastPromotionBy: 'Sales',
    lastPromotionDate: '2024-06-05',
    lastPricePaid: 3800,
    avatar: 'https://picsum.photos/seed/13/100/100',
  },
  {
    id: 'inf-14',
    name: 'Ravi Kumar',
    platforms: [{
        platform: 'Instagram',
        channelName: "Ravi's Tech Telugu",
        channelLink: 'https://instagram.com/ravistechtelugu',
        handle: 'ravistechtelugu',
        averageViews: 110000,
    }],
    category: 'Tech',
    language: 'Telugu',
    email: 'ravi.kumar@example.com',
    mobile: '+91-9876543210',
    pan: 'YZAB8901M',
    agency: {
      name: 'South Digital',
      contact: 'contact@southdigital.com',
    },
    lastPromotionBy: 'Marketing',
    lastPromotionDate: '2024-05-18',
    lastPricePaid: 3000,
    avatar: 'https://picsum.photos/seed/14/100/100',
  },
];

export const campaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Summer Fashion Launch',
    department: 'Sales',
    deliverables: '2 Instagram Posts, 3 Stories',
    date: '2024-06-15',
    pricePaid: 3500,
    averageViews: 80000,
    influencerId: 'inf-2',
    approvalStatus: 'Approved',
  },
  {
    id: 'camp-2',
    name: 'New Gadget Unboxing',
    department: 'Marketing',
    deliverables: '1 YouTube Video',
    date: '2024-05-20',
    pricePaid: 5000,
    averageViews: 150000,
    influencerId: 'inf-1',
    approvalStatus: 'Pending',
  },
  {
    id: 'camp-3',
    name: 'Comedy Skit Collab',
    department: 'Product',
    deliverables: '3 TikTok Videos',
    date: '2023-11-10',
    pricePaid: 2000,
    averageViews: 500000,
    influencerId: 'inf-3',
    approvalStatus: 'Approved',
  },
  {
    id: 'camp-4',
    name: 'Gaming Tournament Stream',
    department: 'Marketing',
    deliverables: '4 hour stream on Twitter',
    date: '2024-07-01',
    pricePaid: 4200,
    averageViews: 45000,
    influencerId: 'inf-4',
    approvalStatus: 'Approved',
  },
  {
    id: 'camp-5',
    name: 'Lifestyle Vlog Series',
    department: 'Brand',
    deliverables: '3 YouTube Videos',
    date: '2024-04-22',
    pricePaid: 6000,
    averageViews: 250000,
    influencerId: 'inf-5',
    approvalStatus: 'Rejected',
  },
  {
    id: 'camp-6',
    name: 'Japanese Food Tour',
    department: 'Marketing',
    deliverables: '5 Instagram Posts',
    date: '2024-02-18',
    pricePaid: 2800,
    averageViews: 120000,
    influencerId: 'inf-6',
    approvalStatus: 'Approved',
  },
];
